### ISSUE TITLE
Investigate possibility to use AWS ALB instead of NGINX

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#10]
This will offload the traffic from EKS cluster to AWS ALB and make certificate management even more convenient.

**Comment by rkandratsiuk** [comment]
Just generate  a TLS via Route53, add it to a new k8s svc type:LoadBalancer and change DNS A record. 
Maintaining all rewrite rules will be in a ingresses rules.
