### ISSUE TITLE
Integrate OpenRPC with Glif endpoints

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#105]
https://inspector.open-rpc.org/
https://github.com/filecoin-project/lotus/pull/4711

**Comment by sergey989** [comment]
https://playground.open-rpc.org/?schemaUrl=https://gist.githubusercontent.com/openworklabbot/44dd022c3214a17deeebf142613fb363/raw/de8982b4c72301f407ccc905dfaaa2f524bbf9ee/lotus-api.json

**Comment by sergey989** [comment]
https://github.com/filecoin-project/lotus/tree/master/build/openrpc
