### ISSUE TITLE
Upgrade Kubernetes to version 1.17

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#11]
According to this [documentation](https://github.com/kubernetes-csi/external-snapshotter/blob/release-2.1/README.md) version 1.17 will allow us to introduce the disk snapshotting feature to create a backup-and-restore mechanism that will drastically increase the client onboarding time.

ETA: 2-16 hours

**Comment by sergey989** [comment]
updated to:
- Control plane 1.17
- CoreDNS  1.6.6
- KubeProxy 1.17.7
- aws-node 1.6.3
- cluster-autoscaler 1.18.2
