### ISSUE TITLE
Build CI to automate publishing of OpenRPC playground API to Glif endpoints

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#128]
Folllow up: #105 
We need a way to automatically post https://github.com/filecoin-project/lotus/tree/master/build/openrpc OpenRPC files to our Glif github page

**Comment by sergey989** [comment]
Job lotus-gist-api-json in jenkins will check every hour and update data, if new tag in lotus repository has version like v*.
https://playground.open-rpc.org/?schemaUrl=https://gist.githubusercontent.com/openworklabbot/44dd022c3214a17deeebf142613fb363/raw/lotus-api.json
