### ISSUE TITLE
[calibnet] - publish internal calibrationnet snapshot

### ISSUE THREAD

**Issue by sergey989** [protofire/Filecoin-node-hosting-management#135]

**Comment by sergey989** [comment]
lotus daemon --halt-after-import --import-snapshot https://dev.node.glif.io/calibrationapi/ipfs/8080/ipfs/$(curl -s https://gist.githubusercontent.com/openworklabbot/95da15b014ffc3b5a170485001f46abd/raw/snapshot.log)

**Comment by ArseniiPetrovich** [comment]
For some reason this IFPS snapshot doesn't work

**Comment by mur-me** [comment]
Fixed IPFS snapshot - problem was with wrong link on https://gist.github.com/openworklabbot
from: https://node.glif.io/space00/ipfs/8080/ipfs/<CID>
to: https://dev.node.glif.io/calibrationapi/ipfs/8080/ipfs/<CID>
