### ISSUE TITLE
Clean old Helm secrets from all namespaces

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#144]
There is a known bug that Helm start working slower when contains a lot of "previous versions" stored in Kubernetes secrets. The task is to delete all old versions, keeping the 3 latest versions only.
Also, investigate whether it is possible to configure Helm in such way, so it will be keeping 3 version only always.

**Comment by dzmitrykliapkou** [comment]
It can be performed automatically by setting `--history-max` flag while upgrading each release with `helm upgrade`.

```
--history-max int              limit the maximum number of revisions saved per release. Use 0 for no limit (default 10)
```

**Comment by mur-me** [comment]
I've added this into https://github.com/glifio/filecoin-chart/pull/51, please review

**Comment by mur-me** [comment]
this one was merged
