### ISSUE TITLE
[archive nodes] - placehloder strory about 16TB limitation for pvc with ebs storage class - comparasion of LLVM and io2 Block Express disks and EFS

### ISSUE THREAD

**Issue by mur-me** [protofire/Filecoin-node-hosting-management#164]
Migrating lotus data from EBS to EFS:

**Description:**
EBS has a general hard limit of 16Tb per data; the Filecoin blockchain almost reached that capacity.
Acceptance criteria:

- During internal brainstorming inside the Protofire team, we noted a few key goals that we want to achieve:
- to find a way/solution that allows us to remove the 16Tb bottlenecked limit.
- to resolve the 16Tb limit as reduce and/or excluding hand-management after the release of the solution.

**Solution:**
- Migrating data from AWS EBS datastore to AWS EFS is the best available option.
- Rewriting the lotus helm chart with adding new EFS functionality logic.
- Deploying new code to both calibration and mainnet infrastructures.

**Comment by mur-me** [comment]
### Old ideas, could be ignored.

This comment is just a placeholder for them.
My findings for RAID0 will be below:
* [eks-nvme-ssd-provisioner.sh could be rewritten and used for usual ebs formating](https://github.com/brunsgaard/eks-nvme-ssd-provisioner/blob/master/eks-nvme-ssd-provisioner.sh)
* [This issue have a lot of ideas how to create RAID0, but again NVMe](https://github.com/kubernetes/kops/issues/429)
* [good example about how RAID mapping could be done, but here local NVMes are used](https://github.com/banzaicloud/pipeline/blob/master/templates/eks/amazon-eks-nodepool-cf.yaml#804)
* [idea how to test IOPS](http://nicolasduminil.blogspirit.com/archive/2019/01/14/devops-on-demand-disk-storage-in-aws-3128464.html)

**Comment by mur-me** [comment]
`io2 Block express` ebs volume was chosen as preferable one instead of llvm of two gp3 disks.
Key points for `io2 Block express`:
* ebs snapshots will be available from the box by default
* easier to manager than logic volumes, llvm will bring a lot of overhead like managing of llvm snapshots and store them somewhere instead of native solutions

**Comment by mur-me** [comment]
Our tactic for the migration on new disks will be like that - *should be discussed*:
I'll divide our action into two phases - Phase 1 aka Lunch of new instance and migration, Phase 2 - measurement of manual disk resizing. 

> Manul disk resizing should be done due to `You can't modify the size or provisioned IOPS of an io2 volume that is attached to an R5b, X2idn, and X2iedn instance.`
Link -> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/modify-volume-requirements.html

Phase 1:
- [ ]     Start new R5B instance via eksctl
- [ ]     Make snapshot of data volume on the old space00 node - already done by cron job  
- [ ]     Make new volume from that snapshot use 18000 GB instead of 16000 GB
- [ ]     Cordon old node and move space00 pod to new instance and start to use new volume on the new instance *will check this*
- [ ]     *TODO: Here should be list of changes in helm charts*
- [ ]     Stop old instance and old disk

Phase 2:
- [ ]     Start to measure how much time it should take to swap volumes - *will add info*

**Comment by witnsby** [comment]
The main idea is to use EFS (NFS) system to breakthrough ebs limitations
