### ISSUE TITLE
Add logging solution to the cluster

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#25]
Logging is as important thing as monitoring when it comes to the cluster stability. We need to deploy a centralized logging solution.

**Comment by eshon** [comment]
@ArseniiPetrovich 
1. Lotus has [some Prometheus endpoints](https://github.com/filecoin-project/lotus/search?q=prometheus&type=Issues)
1. You might find the PL Sentinel (network analysis) team's monitoring tools helpful: https://github.com/filecoin-shipyard/telegraf-lotus. If you'd like to chat with them about any of this you can ask placer14 in [fil-infra-chainwatch](https://filecoinproject.slack.com/archives/C01754RMW3V)

Please document how you set up the monitoring, Sentinel'd be interested

**Comment by ArseniiPetrovich** [comment]
Thanks, @eshon, I'll keep this in mind, it will be extremely useful when working on task 👍

**Comment by eshon** [comment]
Ah I see https://github.com/protofire/Filecoin-node-hosting-management/issues/21 now

**Comment by ArseniiPetrovich** [comment]
Thanks for approving #21, @eshon. It was necessary for us to complete it before start ;)
