### ISSUE TITLE
Build a bare-metal 128GiB RAM node so it can be a failover hosted endpoint

### ISSUE THREAD

**Issue by ArseniiPetrovich** [protofire/Filecoin-node-hosting-management#52]

**Comment by rkandratsiuk** [comment]
This host will be consist of:
- lotus daemon
- filecoin-proxy-cache
- nginx
- prometheus node exporter
- fluentd as a logging agent

ansible like software provisioning tool

Are we are really need in a this solution? 
@ArseniiPetrovich
